name: "Feature Request"
description: "Propose new features or share ideas"
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Use this template if you have a new feature proposal or idea for the Suika Game.

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: Briefly describe the proposed feature
      placeholder: |
        Example: Add particle effects when fruits merge
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation & Background
      description: Explain why this feature is needed and what problem it solves
      placeholder: |
        Example: The current merge animation is too plain. Adding particle effects
        would make the game feel more polished and satisfying, similar to the original
        Suika Game.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Implementation
      description: If you have ideas on how this should be implemented, describe them here
      placeholder: |
        Example:
        - Use Bevy's particle system or bevy_hanabi
        - Spawn particles at merge point with fruit colors
        - Particles should burst outward and fade
        - Sound effect should play simultaneously
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any other approaches or alternatives you've considered
      placeholder: |
        Example:
        - Simple scale animation (simpler approach)
        - Screen shake effect instead of particles
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the category this feature relates to
      options:
        - "Physics & Collision"
        - "Fruit Merging System"
        - "Scoring System"
        - "UI & HUD"
        - "Input Controls"
        - "Audio (BGM/SFX)"
        - "Visual Effects & Particles"
        - "Game Modes"
        - "Accessibility"
        - "Performance & Optimization"
        - "Developer Tools"
        - "Asset Management"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Proposer's Perspective)
      description: How important do you think this feature is?
      options:
        - "P0: Essential (Game cannot function without this)"
        - "P1: Important (Core mechanic or standard feature)"
        - "P2: Nice to have (Enhances experience)"
        - "P3: Would be nice (Polish or extra feature)"
    validations:
      required: false

  - type: dropdown
    id: phase
    attributes:
      label: Implementation Phase (Suggestion)
      description: In which phase do you think this should be implemented? (Ref: docs/06_implementation_plan.md)
      options:
        - "Phase 1-3: Core Setup (Project structure, basic systems)"
        - "Phase 4-6: Game Logic (Physics, merging, scoring)"
        - "Phase 7-9: Polish (UI, Audio, Effects)"
        - "Phase 10: Optimization & Testing"
        - "Phase 11: Asset Integration"
        - "Future: Post-release features"
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Reference Implementations & Similar Features
      description: If there are implementation examples in other games, describe them
      placeholder: |
        - Original Suika Game: Uses particle burst effects on merge
        - 2048: Uses smooth scale animation
        - Fruit Merge: Has rainbow particle effects
    validations:
      required: false

  - type: textarea
    id: design-docs
    attributes:
      label: Related Design Documents
      description: If there are related design documents or Issues, describe them
      placeholder: |
        - Mentioned in docs/03_physics_rendering.md Section 4
        - Related to #123 (particle system implementation)
    validations:
      required: false

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Information
      description: Any other useful information
      placeholder: |
        - This feature would significantly improve game feel
        - Implementation difficulty is expected to be moderate
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before submitting
      options:
        - label: I've confirmed this feature hasn't been proposed in existing Issues
          required: true
        - label: I've checked the documentation and confirmed this isn't already planned
          required: false
        - label: This is a new feature proposal, not a bug fix
          required: false
